### PR TITLE
Feature/unclear task input

### PR DESCRIPTION
**Pull request by yiw008**
### Administrative Info 
Insert a list of all the issues this Pull Request closes below 

- Closes <#66>

Make sure your branch name conforms to: \<feature/bug/admin>/description or the PR will not pass 

### Changes 
What changes did you make?

- Add a tooltip so that users can know what # means
- Modify the description of the form since the length of a pomo-session would not be exactly 25 minutes
  

### Checklist for Review
- [ ] PR's tests are not brittle (will not break if implementation slightly changes)
- [ ] Test cases have a description as to what they test

### Lint Changes 
If there are any rules your turned off on the linter, write them below 
- N/A
  
### Reviewers 
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and peformance of the website. Check for consistency of code style.

### CODE REVIEW

**Comment by AW0723** [comment]
I think we should also rename the # column. Maybe something like est. pomos

**Review by nicleee666 — APPROVED** [review]
I think showing tips while hovered over is sufficient for users, implementation looks good.
 However, I believe adding this into the tutorial is necessary.

**Comment by yiw008** [comment]
> I think we should also rename the # column. Maybe something like est. pomos

The task part would have less space.


> I think showing tips while hovered over is sufficient for users, implementation looks good. However, I believe adding this into the tutorial is necessary.

The tutorial has this part originally.

**Review by AW0723 — APPROVED** [review]
Looks good

**Comment by mmjiang-ucsd** [comment]
Changing "#" to "# of Pomos" would be good

**Pull request merged**
