### PR TITLE
hide buttons

### PR DESCRIPTION
**Pull request by nicleee666**
### Administrative Info 
Insert a list of all the issues this Pull Request closes below 

- Closes <#73>

Make sure your branch name conforms to: \<feature/bug/admin>/description or the PR will not pass 

### Changes 
What changes did you make?
- hide and show buttons 

- TODO 
  
### Checklist for Review
- [ ] PR's tests are not brittle (will not break if implementation slightly changes)
- [ ] Test cases have a description as to what they test

### Lint Changes 
If there are any rules your turned off on the linter, write them below 
- TODO 
  
### Reviewers 
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and peformance of the website. Check for consistency of code style.

### CODE REVIEW

**Review by yiw008 — APPROVED** [review]

**Comment by nicleee666** [comment]
One unit test keeps failing on GitHub but not on my terminal I tried so many commits to fix it.

**Comment by yiw008** [comment]
```
localStorage.setItem('startDateTime', new Date(today.getFullYear() + 1, today.getMonth() + 1, today.getDate() + 1, 3, 0, 0));
Stats = new Statistics();
expect(Stats.dataToCompressExists()).toBeFalsy();
```
I guess this is because today is in the last days of May - '+ 1' may not work. 
Just a guess. I'm trying to figure out this.

**Comment by yiw008** [comment]
Just took an experiment in #121.

**Comment by yiw008** [comment]
Fixed, but I can't ensure that we won't have similar problems again in the future.

**Comment by AW0723** [comment]
We should probably add a fade transition to the buttons

**Review by nickkro25 — APPROVED** [review]
Looks good, all buttons get hidden on working time and get unhidden during break time/ timer not running

**Pull request merged**
