### PR TITLE
Fixed Weird Refresh Transition in Dark Mode

### LINKED ISSUE #102: [Bug Report] Weird Transition in Dark mode when refreshing
**Describe Bug**
When dark mode is turned on, refreshing the page would result in a short color transition

**Steps to recreate the issue**
- Turn on dark mode
- Refresh

**Additional Documentation**
Add any pictures/gifs as necessary to demonstrate

https://user-images.githubusercontent.com/64997746/170594551-4c57d01f-9b11-4759-a47f-def73984410f.mp4

### PR DESCRIPTION
**Pull request by AW0723**
### Administrative Info 
Insert a list of all the issues this Pull Request closes below 

- Closes #102 

Make sure your branch name conforms to: \<feature/bug/admin>/description or the PR will not pass 

### Changes 
What changes did you make?

- Moved inline js to the end
- Update other elements upon refresh
  
### Checklist for Review
- [ ] PR's tests are not brittle (will not break if implementation slightly changes)
- [ ] Test cases have a description as to what they test

### Lint Changes 
If there are any rules your turned off on the linter, write them below 
- TODO 
  
### Reviewers 
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and peformance of the website. Check for consistency of code style.

### CODE REVIEW

**Comment by AW0723** [comment]
Currently I've only managed to fix this in Chrome, but it doesn't work in Firefox yet

**Review by yiw008 — APPROVED** [review]
Works for Chrome.

**Comment by yiw008** [comment]
Maybe we can modify transition time

**Review by yiw008 — COMMENTED** [review]
Maybe we can modify the transition duration

**Comment by yiw008** [comment]
Actually, it still doesn't work sometimes in Chrome

https://user-images.githubusercontent.com/81718264/170818269-c480cede-8a12-4e6f-ad67-2313f5777ab7.mp4

**Comment by AW0723** [comment]
> Actually, it still doesn't work sometimes in Chrome. Maybe we can change the initial color to white to make the transition look better if we can't fix this.
> 
>  1.mp4

Yeah I noticed that, I think our frenemy said something about using .darkMode classes in css, but I feel like it would be quite a bit of work to restructure. I'll prioritize other issues before coming back to this one, because I think it's not a huge impact on the user experience (users don't really need to refresh frequently)

**Comment by yiw008** [comment]
I just made a [Plan B](https://github.com/nickkro25/cse112_team15/tree/bugfix/plan_b_for_refresh_transition) for transition in dark mode.
I added a loading feature so that the weird transition will not show to the user. It works on both Chrome and Firefox.
I think we can't set the background black directly because the page bg color in `:root` is always initially cadetblue when we refresh the page.

https://user-images.githubusercontent.com/81718264/170823825-dbd8c86e-58a5-4706-8de7-41c9d7d8643e.mov

https://user-images.githubusercontent.com/81718264/170823868-61e37e27-227d-403a-b4c7-ab66dd19fb64.mov

**Comment by TheOneGeo** [comment]
I don't think increasing everyone's load times by 2s is a good solution. I agree with Allen, let's come back to this if we have the time.

**Review by TheOneGeo — APPROVED** [review]
Let's use this solution for now. Good work :)

**Review by yiw008 — APPROVED** [review]
> Increasing everyone's load times by 2s doesn't feel like a good solution. I agree with Allen, let's come back to this if we have the time.

👍

**Pull request merged**
