### PR TITLE
Created custom color feat

### PR DESCRIPTION
**Pull request by TheOneGeo**
### Administrative Info 
Insert a list of all the issues this Pull Request closes below 

- Closes < #10, #33  >

Make sure your branch name conforms to: \<feature/bug/admin>/description or the PR will not pass 

### Changes 

- Added HTML color pickers that allow users to pick their colors for the 3 modes (Work, Short, Long)
- Added color changes when switching between the 3 modes
  
### Checklist for Review
- [ ] PR's tests are not brittle (will not break if implementation slightly changes)
- [ ] Test cases have a description as to what they test

### Lint Changes 
If there are any rules your turned off on the linter, write them below 
- TODO 
  
### Reviewers 
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and peformance of the website. Check for consistency of code style.

### CODE REVIEW

**Review by AW0723 — APPROVED** [review]
Looks absolutely amazing :D
We'll need to add support for dark mode, and save the colors in localStorage.

**Review by yiw008 — DISMISSED** [review]

**Comment by mmjiang-ucsd** [comment]
image

The buttons don't seem to change color?

**Comment by yiw008** [comment]
Problem now: set dark mode in short-break and long-break

**Comment by yiw008** [comment]
- store short val & long val
- scroll bar color for stats board: change to page bg color

**Comment by yiw008** [comment]
- when not in dark mode, follow the color the user chose for heading & buttons
- text color changes in the color theme part of settings when the dark mode is on/off
- no delay between transition of text color for the title "Color Theme" and titles of three color pickers

**Comment by AW0723** [comment]
Great work! The tasks look inconsistent in break though.
image

**Comment by yiw008** [comment]
- thinner scroll bar for the table
- task bg color changes according to the color chosen (same to the button/icon color)

**Comment by yiw008** [comment]
- thinner scroll bar for the table
- task bg color changes according to the color chosen (same to the button/icon color)

**Comment by yiw008** [comment]
Commit [900a4c7](https://github.com/nickkro25/cse112_team15/pull/78/commits/900a4c721d951ea9fa9fa6d2aac79d315ee32cdf) fixes Issue #75.

**Comment by mmjiang-ucsd** [comment]
Task color changes to this blue when you change the color 
image

**Comment by yiw008** [comment]
- fix task color
- fix scroll bar color

**Comment by yiw008** [comment]
- index.html
  - Line 136, 140, 141: html validation
  - Line 146-163: restore the color picker, change "colorSelectorDiv" to class for html validation to avoid duplicate id error
- settings.css
  - change "colorSelectorDiv" to class

**Comment by yiw008** [comment]
Just added a feature that the font color changes according to the background color

**Comment by yiw008** [comment]
It seems like we need to add some tests.

**Review by mmjiang-ucsd — APPROVED** [review]

**Review by nickkro25 — APPROVED** [review]
All looks good to me

**Pull request merged**
