### PR TITLE
added light up on hover for top bar buttons

### LINKED ISSUE #96: [Bug Report]light up the button when hovered over
**Describe Bug**
We lost the button light up feature over other bug fixes of the buttons.

**Steps to recreate the issue**
track the issue then fix the bug

### PR DESCRIPTION
**Pull request by efloresCSE**
### Administrative Info 
Insert a list of all the issues this Pull Request closes below 

- Closes #96

Make sure your branch name conforms to: \<feature/bug/admin>/description or the PR will not pass 

### Changes 
What changes did you make?

- Clarified with issue creator that the issue was pertaining to the button on the top right corner so:
- Added functionality to light up buttons on top right corner on hover
  
### Checklist for Review
- [ ] PR's tests are not brittle (will not break if implementation slightly changes)
- [ ] Test cases have a description as to what they test

### Lint Changes 
If there are any rules your turned off on the linter, write them below 
- TODO 
  
### Reviewers 
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and peformance of the website. Check for consistency of code style.

### CODE REVIEW

**Review by yiw008 — DISMISSED** [review]

**Comment by AW0723** [comment]
Personally I like the highlighting effect that the old team had - changing the color of the button. Maybe we should ask what other people think?
https://anshul-birla.github.io/cse110-w21-group28/#

**Comment by mmjiang-ucsd** [comment]
That's a default materialize buttons effect, some of our custom CSS must have broken it

**Review by nickkro25 — CHANGES_REQUESTED** [review]
To be honest the lighting for the buttons seems a bit too bright/responsive. I preferred having no highlight over highlight. I played around with the color and size of the shadows and couldn't find one that I personally liked. Maybe instead of color changing the size could slightly increase/decrease on hover? Idk we can bring it up in meeting

**Comment by yiw008** [comment]
All the old changes are deleted. Here starts the new implementation.

**Comment by yiw008** [comment]
https://user-images.githubusercontent.com/81718264/171101901-d82f8871-0c5f-45ea-bae6-1b0ba9ef033e.mp4


https://user-images.githubusercontent.com/81718264/171101922-eec8f598-dd06-4604-83bb-567f1141ab1d.mp4

**Comment by yiw008** [comment]
- This PR also solves #131.

**Review by mmjiang-ucsd — APPROVED** [review]

**Review by nickkro25 — APPROVED** [review]
LGTM

**Pull request merged**
