### PR TITLE
Task Control Buttons

### LINKED ISSUE #77: [FEATURE REQ] Task List Control Buttons
**Describe Feature**
- Implement up and down arrow buttons to rearrange single tasks in the list.
- Move star button out of the detailed menu, replace star icon with a suitable icon (perhaps a double arrow) to make it more clear that the button is for moving a task to the top of the list.
- Move trash button out of the detailed menu.

**Why is this useful**
- Up and down arrows give the user more control over the order of their tasks in the list.
- Moving the star and trash buttons out of the detailed menu reduce the number of clicks required for the user to perform those actions.

**Additional Requirements**
N/A

### PR DESCRIPTION
**Pull request by mmjiang-ucsd**
### Administrative Info 
- Closes #77 

### Changes 
- Added up and down arrow buttons, lets you shift tasks up and down the list
- Changed star SVG to a double up arrow icon
- Changed trash SVG to a trash icon
  
### Checklist for Review
- [ ] PR's tests are not brittle (will not break if implementation slightly changes)
- [ ] Test cases have a description as to what they test

### Lint Changes 
Nope
  
### Reviewers 
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and peformance of the website. Check for consistency of code style.

### CODE REVIEW

**Comment by mmjiang-ucsd** [comment]
Made a pull request just for visibility. 

- probably going to remove the triple dots to reduce clicks
- need Westley to help out with test cases once finalized
- taking suggestions on button layout and/or design

**Comment by mmjiang-ucsd** [comment]
- added some animations for when tasks are moved around
- replaced triple dot icon and aligned it with the trash and add buttons at the top and bottom of the task list
- fixed a bunch of bugs
- made task list square again (I think this looks better tbh)

**Review by yiw008 — COMMENTED** [review]
When I pin Task 6 in the following video, it flashes above the task list header.

https://user-images.githubusercontent.com/81718264/170812452-b1f82e4a-564e-4f15-bad3-e1e07987d9f6.mp4

**Comment by yiw008** [comment]
Solved.

**Review by yiw008 — APPROVED** [review]

**Review by nicleee666 — APPROVED** [review]
looks good after Yizhou's commit

**Comment by mmjiang-ucsd** [comment]
https://user-images.githubusercontent.com/74376151/170844897-94a88072-4b6b-4f47-a4a2-506d47e40951.mp4
Demo of the changes

**Review by efloresCSE — APPROVED** [review]
Looks Good!

**Pull request merged**
