### PR TITLE
Added transition effects and emphasize curr task

### PR DESCRIPTION
**Pull request by jcpriyanto**
### Administrative Info 
Insert a list of all the issues this Pull Request closes below 

- Closes <#98>

Make sure your branch name conforms to: \<feature/bug/admin>/description or the PR will not pass 

### Changes 
What changes did you make?
- Added transition effect fade in when focus and fade out when un-focus
- Make current task and mode text larger

- TODO 
  
### Checklist for Review
- [ ] PR's tests are not brittle (will not break if implementation slightly changes)
- [ ] Test cases have a description as to what they test

### Lint Changes 
If there are any rules your turned off on the linter, write them below 
- TODO 
  
### Reviewers 
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and peformance of the website. Check for consistency of code style.

### CODE REVIEW

**Review by nickkro25 — APPROVED** [review]
Looks good to me! It breaks a little when task is too long, made an issue on that and working on it.

**Comment by mmjiang-ucsd** [comment]
- We should move the current task above the buttons and below the timer
- Should also make the header the same color as the bg during focus

**Comment by mmjiang-ucsd** [comment]
Header doesn't change to bg color in darkmode because of hardcoded inline css

**Comment by mmjiang-ucsd** [comment]
focus

**Review by yiw008 — APPROVED** [review]

**Comment by mmjiang-ucsd** [comment]
current_task_anim

Added an animation for updating the current task

**Pull request merged**
