### PR TITLE
Feature/custom-timer-length

### PR DESCRIPTION
**Pull request by efloresCSE**
Administrative Info
Insert a list of all the issues this Pull Request closes below

Closes https://github.com/nickkro25/cse112_team15/issues/6 Custom Timer/Break Length
Make sure your branch name conforms to: <feature/bug/admin>/description or the PR will not pass

Changes
What changes did you make?

HTML: Adds custom time group in settings, which allows user to input custom times for focus(pomo), short break and long breaks.
CSS: Styles the above appropriately
JS: Adds proper functionality to limit user input between 1-99, and to only allow whole numbers. Changes timer display based on user input. Saves user custom times on page refresh.
Checklist for Review
 PR's tests are not brittle (will not break if implementation slightly changes)
 Test cases have a description as to what they test
Lint Changes
If there are any rules your turned off on the linter, write them below

TODO
Reviewers
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and peformance of the website. Check for consistency of code style.

### CODE REVIEW

**Comment by mmjiang-ucsd** [comment]
The unit test failure might be because of the package-lock file, see if we can restore the original version from main

**Comment by mmjiang-ucsd** [comment]
Turns out the unit tests are failing because there isn't enough code coverage, aka we need to add tests for our new code

**Comment by yiw008** [comment]
image

**Review by yiw008 — APPROVED** [review]

**Comment by AW0723** [comment]
The timer would flicker if the timer length is changed after timer is started.

To replicate it, start the timer, and change the timer length, the timer display would change to the new timer length for a brief moment and go back to the count down.

**Review by AW0723 — COMMENTED** [review]
The functionality works pretty well, though there's a minor bug where changing the timer length during a count down would cause the timer to flicker. Style-wise, there are a lot of commented out code and temporary comments.

**Review by AW0723 — APPROVED** [review]
Look good to me?

**Pull request merged**
