### PR TITLE
Bugfix: "Delete all" and "add" buttons highlight when hovered

### LINKED ISSUE #163: [Bug Report] "Delete all" and "add" buttons don't highlight when hovered
**Describe Bug**
See title.

**Steps to recreate the issue**
1. Hover mouse over delete all button
2. Hover mouse over add button

**Additional Documentation**
N/A

### PR DESCRIPTION
**Pull request by yiw008**
### Administrative Info 
Insert a list of all the issues this Pull Request closes below 

- Closes #163

Make sure your branch name conforms to: \<feature/bug/admin>/description or the PR will not pass 

### Changes 
What changes did you make?

- "Delete all" and "add" buttons highlight when hovered
  
### Checklist for Review
- [ ] PR's tests are not brittle (will not break if implementation slightly changes)
- [ ] Test cases have a description as to what they test

### Lint Changes 
If there are any rules your turned off on the linter, write them below 
- TODO 
  
### Reviewers 
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and peformance of the website. Check for consistency of code style.

### CODE REVIEW

**Comment by yiw008** [comment]
https://user-images.githubusercontent.com/81718264/172440012-ed694797-0745-448c-85c5-7a65689c7c19.mp4

**Review by mmjiang-ucsd — APPROVED** [review]

**Review by jcpriyanto — APPROVED** [review]
Nice

**Review by nicleee666 — APPROVED** [review]
looks good

**Review by efloresCSE — APPROVED** [review]
LGTM, ty

**Pull request merged**
