### PR TITLE
No more transition for faq & statistics buttons

### PR DESCRIPTION
**Pull request by yiw008**
### Administrative Info 
Insert a list of all the issues this Pull Request closes below 

- Closes <#133>

Make sure your branch name conforms to: \<feature/bug/admin>/description or the PR will not pass 

### Changes 
What changes did you make?

https://user-images.githubusercontent.com/81718264/171069683-fdc047d2-ab70-48d2-b62c-79fca6c134d4.mp4

  
### Checklist for Review
- [ ] PR's tests are not brittle (will not break if implementation slightly changes)
- [ ] Test cases have a description as to what they test

### Lint Changes 
If there are any rules your turned off on the linter, write them below 
- TODO 
  
### Reviewers 
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and peformance of the website. Check for consistency of code style.

### CODE REVIEW

**Review by mmjiang-ucsd — APPROVED** [review]

**Review by AW0723 — APPROVED** [review]
I thought we were going to add transitions to the settings and tour buttons instead of removing transition from faq and stats buttons, but I guess this is fine too

**Comment by AW0723** [comment]
Actually, on branch #126, all buttons have the transition. For some reason, the buttons had different classes in index.html, so I added the same class for all buttons for the fade transition of the buttons, and as a result they all have the minimizing transition as well.

**Comment by yiw008** [comment]
> Actually, on branch https://github.com/nickkro25/cse112_team15/pull/126, all buttons have the transition. For some reason, the buttons had different classes in index.html, so I added the same class for all buttons for the fade transition of the buttons, and as a result they all have the minimizing transition as well.

Which one would you like?
- If you want all the buttons having the minimizing transition, just close this PR without merging, and note Issue #133 in PR #126.
- If you want all the buttons not having the minimizing transition, just approve & merge this PR.

**Comment by PabloGratas** [comment]
I prefer it with no transition, imo. Reviewing to show support for this version 👍

**Review by PabloGratas — APPROVED** [review]

**Comment by AW0723** [comment]
Just a heads up, if we go with having no transitions, the fading transition when the timer starts will be broken.

**Pull request merged**
