### PR TITLE
Feature/auto start option

### LINKED ISSUE #34: [FEATURE REQ] Timer auto-start toggle option
**Describe Feature**
Currently, the timer will automatically transition straight into the next phase when the current phase ends. It would be nice to have the option to let the user choose if the timer automatically transitions or not.

**Why is this useful**
More power to the user, more customizability

**Additional Requirements**
N/A

### PR DESCRIPTION
**Pull request by AW0723**
### Administrative Info 
Insert a list of all the issues this Pull Request closes below 

- Closes #34 

Make sure your branch name conforms to: \<feature/bug/admin>/description or the PR will not pass 

### Changes 
What changes did you make?
- Added an additional option in settings for toggling the functionality
- When this option is enabled, the timer behaves same as before, automatically starts the breaks
- When this option is disabled, the timer doesn't start automatically, and I update the display so that it shows break info (I was thinking about refactoring the display update to a new method called updateDisplay(), not sure if that's necessary)
  
### Checklist for Review
- [ ] PR's tests are not brittle (will not break if implementation slightly changes)
- [ ] Test cases have a description as to what they test

### Lint Changes 
If there are any rules your turned off on the linter, write them below 
- Nope
  
### Reviewers 
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and peformance of the website. Check for consistency of code style.

### CODE REVIEW

**Comment by mmjiang-ucsd** [comment]
Seems like the timer will still automatically go from break into work mode

**Comment by AW0723** [comment]
> Seems like the timer will still automatically go from break into work mode

By default, the auto start option is turned on. If u want the timer to pause after work session is over, u need to turn off the option under settings.

**Comment by mmjiang-ucsd** [comment]
Sorry let me clarify, with the auto start option turned off, focus still starts automatically after a break ends. Break after focus does stop correctly

**Comment by AW0723** [comment]
> Sorry let me clarify, with the auto start option turned off, focus still starts automatically after a break ends. Break after focus does stop correctly

Oh I intentionally made it that way, cause I feel like it defeats the purpose of pomo timer if the user can choose when to start a break. It's like they can take a break for however long they want.

**Review by nickkro25 — APPROVED** [review]
Tested functionality with short and long breaks, everything seemed to be working. Looks good to me.

**Comment by mmjiang-ucsd** [comment]
I would have the focus timer also stop, otherwise the behavior seems inconsistent. I see your point with the break but the way it’s set up now, the user could also just choose to not start their break

**Comment by AW0723** [comment]
> I would have the focus timer also stop, otherwise the behavior seems inconsistent. I see your point with the break but the way it’s set up now, the user could also just choose to not start their break

What if after the focus session ends, the app starts to count up the exceeded time, keeping track of the extra working minutes. (this idea comes from the Forest app)

For example, if the focus session length is set to 25 mins and "count exceeded time" option is enabled, after the user focuses for 25 minutes, the timer starts to count up. Let's say the user works for another 10 mins, then the timer would show +10:00. And working minutes in statistics is updated accordingly. 

I'm not sure if we should also count exceeded break time. If we're going to count exceeded break time, then we could add "resting minutes" in statistics, but that could lead to users taking breaks longer than they should.

**Review by mmjiang-ucsd — APPROVED** [review]
looks good!

**Pull request merged**
